---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    tektonconfig.operator.tekton.dev/pruner: "true"
  name: tekton-resource-pruner
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - args:
                - "tkn pipelinerun delete --keep=100 -f"
              command:
                - /bin/sh
                - -c
              image: ${TEKTON_RESOURCE_PRUNER_IMAGE}@${TEKTON_RESOURCE_PRUNER_SHA}
              imagePullPolicy: IfNotPresent
              name: tekton-resource-pruner
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: FallbackToLogsOnError
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          serviceAccount: cad-tekton-pruner
          serviceAccountName: cad-tekton-pruner
          terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 3600
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cad-tekton-pruner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cad-tekton-pruner-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - watch
      - list
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
    verbs:
      - delete
      - list
      - get
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cad-tekton-pruner-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cad-tekton-pruner-role
subjects:
  - kind: ServiceAccount
    name: cad-tekton-pruner
